apiVersion: 1

datasources:
  # Prometheus metrics from metrics server
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://companies-house-metrics.onrender.com/metrics
    isDefault: true
    editable: true

  # Direct SQLite database access
  - name: SQLite
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /opt/render/project/data/companies.db
    editable: true
